# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160712_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppedimage',
            name='blanked_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.BlankedImage'),
        ),
        migrations.AddField(
            model_name='customimage',
            name='blanked_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.BlankedImage'),
        ),
    ]
