# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160718_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppedimage',
            name='blanked_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='customimage',
            name='blanked_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
